// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8RArRIH3MzWgWCZYg-qap2djCjBBSrJ8',
    appId: '1:784980154847:web:cbd69229c89201ddaa0c6a',
    messagingSenderId: '784980154847',
    projectId: 'xiaozhi-hyper',
    authDomain: 'xiaozhi-hyper.firebaseapp.com',
    storageBucket: 'xiaozhi-hyper.firebasestorage.app',
    measurementId: 'G-8C7GJF7C62',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKt1Jaluv0MnPx4HKYJBe9bRaNt3-y-sI',
    appId: '1:784980154847:android:bfbdff42e4c695d3aa0c6a',
    messagingSenderId: '784980154847',
    projectId: 'xiaozhi-hyper',
    storageBucket: 'xiaozhi-hyper.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDw2eV1-UyzgNHtjRIi92D8mosafi6K1_s',
    appId: '1:784980154847:ios:006bbc62647d4491aa0c6a',
    messagingSenderId: '784980154847',
    projectId: 'xiaozhi-hyper',
    storageBucket: 'xiaozhi-hyper.firebasestorage.app',
    iosBundleId: 'com.example.xiaozhi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDw2eV1-UyzgNHtjRIi92D8mosafi6K1_s',
    appId: '1:784980154847:ios:006bbc62647d4491aa0c6a',
    messagingSenderId: '784980154847',
    projectId: 'xiaozhi-hyper',
    storageBucket: 'xiaozhi-hyper.firebasestorage.app',
    iosBundleId: 'com.example.xiaozhi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8RArRIH3MzWgWCZYg-qap2djCjBBSrJ8',
    appId: '1:784980154847:web:ffd0acf020faa102aa0c6a',
    messagingSenderId: '784980154847',
    projectId: 'xiaozhi-hyper',
    authDomain: 'xiaozhi-hyper.firebaseapp.com',
    storageBucket: 'xiaozhi-hyper.firebasestorage.app',
    measurementId: 'G-288P30WYM7',
  );
}
